### ISSUE TITLE
Add sitemap so search engine results can showcase community and extensions, etc. just a bit better

### ISSUE THREAD

**Issue by thadguidry** [OpenRefine/openrefine.org#276] opened 2024-01-08 04:18 UTC
When folks search "openrefine", many of the search engine results only show the following 4 areas:

```
DownloadDownload OpenRefine. OpenRefine is free software ...
User ManualThis manual is designed to comprehensively walk through ...
Running OpenRefineWith openrefine.exe​. You can run OpenRefine by double-clicking ...
Installing OpenRefineInstall or upgrade OpenRefine​ · The quick version: Install ...
```

And we'd ideally have a sitemap, so that way we can also easily showcase much more important (in my mind) /community (with the Discourse forum) or maybe only the forum? as well as /whats_new and /extensions.  Maybe other things from the footer or top nav?

Here's the plugin:  https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-sitemap

**Comment by tfmorris** [comment] 2024-01-08 21:04
Are you seeing pages which aren't being indexed? Sitemaps help with discoverability, but don't influence prioritization of results. Search engine priorities are driven by searchers, not publishers (and advertisers, of course, but that's a whole 'nother kettle of fish).

**Comment by thadguidry** [comment] 2024-01-09 05:23
@tfmorris That is false information as of about circa ~ 2009, which you probably are not aware of, but that's fine.  Here's some more information:

> Include the URLs in your sitemap that you want to see in Google's search results. Google generally shows the [canonical URLs](https://developers.google.com/search/docs/crawling-indexing/consolidate-duplicate-urls) in its search results, which you can influence with sitemaps. If you have different URLs for mobile and desktop versions of a page, we recommend pointing to only one version in a sitemap. However, if you want to point to both URLs, [annotate](https://developers.google.com/search/docs/crawling-indexing/mobile/mobile-sites-mobile-first-indexing#additional-best-practices) your URLs to indicate the desktop and mobile versions.

- https://developers.google.com/search/docs/crawling-indexing/sitemaps/build-sitemap

**Comment by thadguidry** [comment] 2024-01-09 05:43
I think I see what is going on.  Here's what I'm seeing:

Not seeing Forum (instead I see Community being ranked higher).  But I think that's because of it's subdomain perhaps?  Still it's something I would more appreciate that if someone typed "openrefine help" that the Forum would have higher rank across many search engines, Google, Bing, Yandex, DuckDuckGo, etc.  but I'm just not seeing that.  Perhaps we need to improve the metadata on the Forum?

Not seeing Extensions unless I explicitly ask for them "openrefine extensions", but overall, I think instead the improvement we'd likely want to see for users would be directly on our Downloads page, with a section that says Extensions, and then links to the Extension page?  That seems like a better way to advertise that there are extensions for OpenRefine, because I doubt folks would think about typing "openrefine extensions" as a new user, and much more likely to spot that we have some when they are on the Download page, as long as its prominently displayed there.

**Comment by tfmorris** [comment] 2024-01-09 22:45
> @tfmorris That is false information as of about circa ~ 2009, which you probably are not aware of, but that's fine.

Srsly?

**Comment by mynk2611** [comment] 2024-11-26 12:01
Hi @thadguidry,

I’ve been working on addressing this issue and tried increasing the priority of the specific pages (e.g., /community, /extensions, and /whats_new) in the sitemap. However, despite my efforts, the priority remained the same (0.5) across all pages.

While researching, I came across this discussion over SEO (https://github.com/facebook/docusaurus/issues/2604), which mentions that adding a lastmod field in the sitemap.xml could improve SEO. Currently, the sitemap doesn’t include a lastmod field.

Would it be worth considering adding the lastmod field to enhance SEO for these key pages? I’m happy to hear your thoughts or any recommendations on how best to proceed.

Looking forward to your input!

**Comment by thadguidry** [comment] 2024-11-26 12:51
@mynk2611 you can add the lastmode field, it does help somewhat.  The problem is that of @magdmartin or others maintaining the sitemap either manually or programmatically -because I'm not doing it ;-)

**Comment by wetneb** [comment] 2024-11-26 13:26
I would hope that the sitemap is automatically generated by Docusaurus, I am really not keen to maintain it manually.

**Comment by mynk2611** [comment] 2024-11-26 14:01
Hi @wetneb,

Thanks for your input!
You’re correct—the sitemap is automatically generated. Here’s a screenshot for reference:

<img width="1331" alt="Screenshot 2024-11-26 at 5 19 24 PM" src="https://github.com/user-attachments/assets/27d71c58-de39-495e-bdb8-4ff34b60cba1">

Currently, it doesn’t include the lastmod field. However, by adding a couple of plugins, it can be configured to include this field. Here’s an example of how the sitemap would look with the lastmod field:

<img width="733" alt="Screenshot 2024-11-26 at 7 25 07 PM" src="https://github.com/user-attachments/assets/e3cb9542-bc8f-4fa6-ab29-5d90a354d326">


Would you recommend moving forward with this change to enhance SEO? Looking forward to your thoughts!

**Comment by wetneb** [comment] 2024-11-26 14:03
It depends how hacky the solution is, if it involves "a couple of plugins" I am perhaps vaguely worried that this is pretty complicated. I'd also be happy with waiting for Docusaurus to support this directly. It's probably easier to discuss this with a PR to look at.

**Comment by tfmorris** [comment] 2024-11-27 05:58
I'm assuming that #406 was intended to close this.

**Closed by tfmorris** 2024-11-27 05:58 UTC
Labels: enhancement
