### ISSUE TITLE
Enhance the documentation related to the `cross()` function

### ISSUE THREAD

**Issue by antoine2711** [OpenRefine/openrefine.org#219] opened 2023-04-29 13:26 UTC
The `cross()` function being powerful, to really understand it potential, adding examples and use case to the current documentation would be valuable.

The list of this that could be added:
- [ ] Keep the current example, but emphasises on the fact that this is just to get **one** row.
- [ ] Show that the result of `cross()` is actually an array and that the selection of one row can be done at multiple level ([Owen's explanation](https://github.com/OpenRefine/openrefine.org/pull/218#issuecomment-1525392052)).
- [ ] Show an example with the `join()` function to get the data of many rows at the same time ([Tom's suggestion](https://github.com/OpenRefine/openrefine.org/pull/218#issuecomment-1527859012)).
- [ ] Add an example to show that `cross()` transform every project into an array of line, making the data of any row available with just the row index)
- [ ] Mention that cross() can access data INSIDE the current project.

Feel free to add other propositions.

**Comment by wetneb** [comment] 2023-04-29 14:50
Duplicate of #214 :-)

**Closed** 2023-04-29 15:25 UTC
